### ISSUE TITLE
Portable for WebAR

### ISSUE THREAD

**Issue by pablopalma** [ahmetozlu/Open-Source-Markerless-Augmented-Reality#3]
Hi! This can be portable for WebAR? i.e OpenCV.js or some way to transpile for web?

Thanks,
Pablo.

**Comment by ahmetozlu** [comment]
I used native OpenCV (c++) for this project but the algorithm can be implemented on OpenCV.js for sure. There is not ready solution to migrate this project directly to OpenCV.js, you must to implement the whole pipe-line.
