### ISSUE TITLE
unresolves external symbol __imp_glewInit refrenced in function ARDrawingContext

### ISSUE THREAD

**Issue by MohammadNouri5700** [ahmetozlu/Open-Source-Markerless-Augmented-Reality#4]
Hello 

I have problem when I want to use that
. after run command cmake .  
cmake created sln file and when I build project I have 6 unresolved externals 

<a href="https://ibb.co/qMMnSzG"><img src="https://i.ibb.co/27769w2/Capture.png" alt="Capture" border="0"></a>

**Comment by ahmetozlu** [comment]
Can you try to build the project using OpenCV – 2.4.11? This should work.
