### ISSUE TITLE
What version of opencv do you use

### ISSUE THREAD

**Issue by StoneClose** [ahmetozlu/Open-Source-Markerless-Augmented-Reality#6]
may i ask you What version of opencv do you use?when i run you code in oppencv3.4.0 i meet some problem such as :1、cv::Ptr<cv::FeatureDetector>      detector = new cv::ORB(1000),2、cv::Ptr<cv::DescriptorExtractor> extractor = new cv::FREAK(false, false),   it reminded me that Objects of abstract class type are not allowed

**Comment by callmeray-mt** [comment]
I met the same problem with OpenCV4, have you found a solution? Thanks

**Comment by ahmetozlu** [comment]
You can build the project using CMakeLists.txt which contains all the versions for the used libraries.

**Comment by ahmetozlu** [comment]
Also, you can build the project using OpenCV – 2.4.11.
